#!/usr/bin/env bash
if [ "$#" -ne 1 ]; then
    echo "error: no configuration file"
    exit 1
fi

if [ ! -d /data ]; then
    echo "error: /data directory is missing (did you forget -v or --mount?)"
    exit 1
fi

cd /data

INI_FILE=$1
source <(grep -F '=' $INI_FILE)

echo "Downloading missing files (configuration: $INI_FILE)"
printf " wget options   %s\n" "$wget_options"
printf " catalog files  %s\n" "$catalogs"
printf " date range     %s/%s\n" "$from_date" "$to_date"

/opt/bashdatacatalog/bashdatacatalog $(echo $catalogs) fetch && \
/opt/bashdatacatalog/bashdatacatalog $(echo $catalogs) list-missing url > /tmp/download-list.txt && \
printf " missing files  %s\n\n" $(wc -l < /tmp/download-list.txt) && \
printf "Starting downloads.\n"
wget -i /tmp/download-list.txt -x -nH -nv $(echo $wget_options)
