#!/usr/bin/env bash
if [ "$#" -ne 1 ]; then
    echo "error: no configuration file"
    exit 1
fi

INI_FILE=$1
source <(grep -F '=' $INI_FILE) # data

if [ ! -d "$data_directory" ]; then
    echo "error: invalid data directory '$data_directory'"
    exit 1
fi

cd $data_directory

echo "Downloading missing files (configuration: $INI_FILE)"
printf " data directory   %s\n" "$data_directory"
printf " catalog files    %s\n" "$catalogs"
printf " index threshold  %s\n\n" "$index_threshold"

bashdatacatalog $(echo $catalogs) admin-autoindex $index_threshold
