#!/usr/bin/env bash
if [ "$#" -ne 1 ]; then
    echo "error: no configuration file"
    exit 1
fi

INI_FILE=$1
source <(grep -F '=' $INI_FILE) # data

if [ ! -d "$data_directory" ]; then
    echo "error: invalid data directory '$data_directory'"
    exit 1
fi

cd $data_directory

echo "Downloading missing files (configuration: $INI_FILE)"
printf " wget options    %s\n" "$wget_options"
printf " data directory  %s\n" "$data_directory"
printf " catalog files   %s\n" "$catalogs"
printf " date range      %s/%s\n" "$from_date" "$to_date"

bashdatacatalog $(echo $catalogs) fetch && \
bashdatacatalog $(echo $catalogs) list-missing url $from_date $to_date > /tmp/download-list.txt && \
printf " missing files  %s\n\n" $(wc -l < /tmp/download-list.txt) && \
printf "Starting downloads.\n" && \
wget -i /tmp/download-list.txt -x -nH -nv $(echo $wget_options)
