#!/usr/bin/env bash
if [ ! -z ${DEBUG+x} ]; then
    set -x
fi
USAGE="""Lists the missing assets. Missing assets are files that are present in the 
collection's metadata, but absent on the local file system.    

Usage:

  bashdatacatalog-listmissing

    Lists the missing files in the local the collection.

  bashdatacatalog-listmissing {-h | --help}
  
    Prints this help message.
"""

if [[ ( $* == --help ) ||  ( $* == -h ) ]]; then 
   echo "$USAGE"
   exit 1
fi 

FILE_LIST=$(mktemp)
find -L . -name .asset_patches -prune -o -type f \( ! -name '\.*' \) -print | sort > $FILE_LIST

awk -F ' +' '{print $2}' .assets.md5 | sed 's/^\*//g' | grep -v -F -f $FILE_LIST

rm -f $FILE_LIST