#!/usr/bin/env bash
if [ ! -z ${DEBUG+x} ]; then
    set -x
fi
set -u

USAGE="""Opens '.temporal_assets.sed' for editing. The text editor is controlled by the
\$EDITOR environment variable. The new temporal asset index is printed at the end.

Usage:

  bashdatacatalog-edittemporal

    Opens '.temporal_assets.sed' for editing.

  bashdatacatalog-edittemporal {-h | --help}

    Prints this help message. 

Editing '.temporal_assets.sed':

  This file is a sed script that generates the temporal index of temporal 
  assets in the collection. The input is the file list of collection assets, 
  such as
    
    ./file1
    ./subdir/file-20181001
    ./subdir/file-20191001

  The script should print 'DATE PATH' for every temporal asset in the 
  collection. The following sed script would print the temporal index of 
  the date-stamped files in './subdir/'.

    s#\\./subdir/file-\\(201[89]\\)\\([0-1][0-9]\\)\\([0-3][0-9]\\)#\\1-\\2-\\3 \\0#p

  Make sure that the LHS captures the entire path so that \\0 prints the
  path to the file. You can have multiple sed expressions in 
  '.temporal_assets.sed'. 
  
  The resulting temporal index is
    
    2018-10-01 ./subdir/file-20181001
    2018-10-01 ./subdir/file-20191001
"""

if [[ ( $* == --help ) ||  ( $* == -h ) ]]; then 
   echo "$USAGE"
   exit 1
fi 

echo "Editing '.temporal_assets.sed' (editor: $EDITOR)"
$EDITOR .temporal_assets.sed
echo "Finished editing. The new temporal index of files in the cwd is shown below."
echo ""
find . -name .asset_patches -prune -o -type f \( ! -name '\.*' \) -print | sort | sed -n -f .temporal_assets.sed
