#!/usr/bin/env bash
if [ ! -z ${DEBUG+x} ]; then
    set -x
fi
set -u

USAGE="""Fetches collection metadata from a remote. This can be used to initialize 
or update the collection metadata of the CWD.  

Usage:

  bashdatacatalog-fetch URL

    URL:    The URL of the remote collection. The remote collection's metadata 
            is downloaded to the CWD.

  bashdatacatalog-fetch {-h | --help}
  
    Prints this help message.
"""

if [[ ( $* == --help ) ||  ( $* == -h ) || $# -eq 0 ]]; then 
   echo "$USAGE"
   exit 1
fi 

function download_file() {
    URL=$1
    FILE_PATH=$2
    OK_CODES=$3
    HTTP_CODE=$(curl -f --write-out "%{http_code}" --silent -k -n -L -g --url $URL -o $FILE_PATH --create-dirs)
    if echo "$HTTP_CODE" | grep -q "$OK_CODES" ; then
        return 0
    else
        return 1
    fi
}

download_file $1/.assets.md5 .assets.md5 "000|2[0-9][0-9]" || ( echo "Failed to download '.assets.md5' from $1"; exit 1 )

download_file $1/.temporal_assets.sed .temporal_assets.sed "000|2[0-9][0-9]\|404"
