#!/usr/bin/env bash
if [ ! -z ${DEBUG+x} ]; then
    set -x
fi
set -e
set -u

echo "Starting self test. Any error indicate that the test failed."

BDC_DIR=$(realpath $(dirname "$0"))/..
BDC_SANDBOX_DIR=$BDC_DIR/sandbox

cd $BDC_SANDBOX_DIR

bashdatacatalog catalog*.csv admin-cleanindex

[ ! -f collection1/.assets.md5 ] || (echo "self test failed" ; exit 1)
[ ! -f collection2/.assets.md5 ] || (echo "self test failed" ; exit 1)

bashdatacatalog catalog*.csv admin-autoindex

TEMP_FILE=$(mktemp)
echo $TEMP_FILE >> tempfiles.txt
TEMP_FILE_2=$(mktemp)
echo $TEMP_FILE_2 >> tempfiles.txt

# Check that collection1/.assets.md5 is it's expected value
cat > $TEMP_FILE << EOF
a5890ace30a3e84d9118196c161aeec2 *./file1
e555d324f7aa42e894fc9e2bf484c7dc *./file2
e76fa6089e1b4cffd1d469bf17389c21 *./file3
d096b4ac2213e3b843f4d04fa44ef648 *./sub1/subfile1
9db5e7c4668f7154965a9b5ce2193677 *./sub1/subfile2
ca45002335a51f30d1fe98019b8c1915 *./sub1/subfile3

EOF

diff -B $TEMP_FILE collection1/.assets.md5


# Check that collection1/.assets.md5 is it's expected value
cat > $TEMP_FILE << EOF
d096b4ac2213e3b843f4d04fa44ef648 *./2018/file-20181005
9db5e7c4668f7154965a9b5ce2193677 *./2018/file-20181105
ca45002335a51f30d1fe98019b8c1915 *./2018/file-20181205
d096b4ac2213e3b843f4d04fa44ef648 *./2019/file-20190203
9db5e7c4668f7154965a9b5ce2193677 *./2019/file-20190403
ca45002335a51f30d1fe98019b8c1915 *./2019/file-20190803
a5890ace30a3e84d9118196c161aeec2 *./file1
e555d324f7aa42e894fc9e2bf484c7dc *./file2
a5890ace30a3e84d9118196c161aeec2 *./file3

EOF

diff -B $TEMP_FILE collection2/.assets.md5

cat > $TEMP_FILE << EOF
./collection1/file1
./collection1/file2
./collection1/file3
./collection1/sub1/subfile1
./collection1/sub1/subfile2
./collection1/sub1/subfile3
./collection2/2019/file-20190203
./collection2/2019/file-20190403
./collection2/file1
./collection2/file2
./collection2/file3
EOF

bashdatacatalog catalog1.csv list-assets rsync 2019-01 2019-05 > $TEMP_FILE_2

diff -B $TEMP_FILE $TEMP_FILE_2

cat > $TEMP_FILE << EOF
./collection2/2019/file-20190203
./collection2/2019/file-20190403
./collection2/file1
./collection2/file2
./collection2/file3
EOF

bashdatacatalog collection2 list-assets relative 2019-01 2019-05  > $TEMP_FILE_2

diff -B $TEMP_FILE $TEMP_FILE_2


echo "Finished self test. (status: TESTS PASSED)"
