#!/usr/bin/env bash
set -u

function download_file() {
    URL=$1
    FILE_PATH=$2
    OK_CODES=$3
    HTTP_CODE=$(curl --write-out "%{http_code}" --silent -k -n -L -g --url $URL -o $FILE_PATH --create-dirs)
    if echo "$HTTP_CODE" | grep -q "$OK_CODES" ; then
        return 0
    else
        return 1
    fi
}

download_file $1/.assets.md5 .assets.md5 "2[0-9][0-9]" || ( echo "Failed to download '.assets.md5' from $1"; exit 1 )

download_file $1/.temporal_assets.sed .temporal_assets.sed "2[0-9][0-9]\|404"
