#!/usr/bin/env bash

ASSETS=$(mktemp)
awk -F ' +' '{print $2}' .assets.md5 | sed 's/^\*//g' > $ASSETS

TEMPORAL_ASSETS=$(mktemp)
awk -F ' +' '{print $2}' .assets.md5 | sed 's/^\*//g' | sed -n -f .temporal_assets.sed | awk -F ' +' '{print $2}' > $TEMPORAL_ASSETS

grep -v -F -f $TEMPORAL_ASSETS $ASSETS

rm -f $TEMPORAL_ASSETS $ASSETS