#!/usr/bin/env bash
if [ ! -z ${DEBUG+x} ]; then
    set -x
fi

ASSETS=$(mktemp)
cat - > $ASSETS

if [ ! -f .temporal_assets.sed ]; then
    cat $ASSETS
    exit 0
fi

TRIM_LIST=$(mktemp)
TEMPORAL_ASSETS=$(mktemp)
sed -n -f .temporal_assets.sed $ASSETS > $TEMPORAL_ASSETS

if [ $# -ge 1 ]; then
    awk -F ' +' -v threshold=$1 '{ if($1 < threshold) print $2 }' $TEMPORAL_ASSETS >> $TRIM_LIST
fi

if [ $# -ge 2 ]; then
    awk -F ' +' -v threshold=$2 '{ if($1 > threshold) print $2 }' $TEMPORAL_ASSETS >> $TRIM_LIST
fi

grep -v -F -f $TRIM_LIST $ASSETS

rm -f $TEMPORAL_ASSETS $TRIM_LIST $ASSETS