#!/usr/bin/env bash

# Generate a file list
FILE_LIST=$(mktemp)
find . -name .asset_patches -prune -o -type f \( ! -name '\.*' \) -print | sort > $FILE_LIST

# Generate a "staged" copy of .assets.md5 
STAGED_ASSETS=$(mktemp)

# Generate a list of files to check
PROCESS_LIST=$(mktemp)

if [ $# -gt 0 ]; then
    IGNORE_THRESHOLD=$1

    # Generate ignore-list for temporal assets older than 
    IGNORE_LIST=$(mktemp)
    cat $FILE_LIST | sed -n -f .temporal_assets.sed | awk -F' +' -v ignore_lt="$IGNORE_THRESHOLD" '{if (ignore_lt >= $1){print $2}}' > $IGNORE_LIST

    # Carry-over ignored entries from previous .assets.md5
    grep -s -F -f $IGNORE_LIST .assets.md5 > $STAGED_ASSETS

    # Generate the list of files to process (calculate MD5 sums for)
    cat $FILE_LIST | grep -v -F -f $IGNORE_LIST > $PROCESS_LIST

    rm -f $IGNORE_LIST
else
    # Generate the list of files to process (calculate MD5 sums for)
    cat $FILE_LIST > $PROCESS_LIST
fi


# Generate a "staged" copy of .assets.md5
cat $PROCESS_LIST | xargs md5sum -b >> $STAGED_ASSETS
sort -k2 -o $STAGED_ASSETS $STAGED_ASSETS

# Calculate diff to .assets.md5
DIFF_FILE=$(mktemp)
diff -Nu .assets.md5 $STAGED_ASSETS > $DIFF_FILE
if [ $? -ne 0 ] ; then
	mkdir -p .asset_patches
	cp $DIFF_FILE .asset_patches/$(date -u +"%FT%H%MZ").patch
fi

# Commit .assets.md5
mv $STAGED_ASSETS .assets.md5

rm -f $FILE_LIST $STAGED_ASSETS $PROCESS_LIST $DIFF_FILE